import { Spots } from "@prisma/client";
import { NewEmotion, NewMood, NewSymptom } from "protocols";

const spotId = {
    root: 1,
    sacral: 2,
    solarPlexus: 3,
    heart: 4,
    throat: 5,
    front: 6,
    crown: 7,
}

const newMoods: NewMood[] = [
    { name: 'Great', color: '#C7FACB' },
    { name: 'Good', color: '#DDEDB7' },
    { name: 'Meh', color: '#FFEDA5' },
    { name: 'Bad', color: '#FFDDAF' },
    { name: 'Angry', color: '#FFD3CA' },
];

const newSpots: Spots[] = [
    { id: 7, name: 'Crown', color: '#AD61FA' },
    { id: 6, name: 'Front', color: '#527DFF' },
    { id: 5, name: 'Throat', color: '#5CE1E6' },
    { id: 4, name: 'Heart', color: '#7ED957' },
    { id: 3, name: 'Solar Plexus', color: '#FFDE59' },
    { id: 2, name: 'Sacral', color: '#FF914D' },
    { id: 1, name: 'Root', color: '#FF5757' },
];

const newEmotions: NewEmotion[] = [
    { name: 'Admiration', color: '#640d14' },
    { name: 'Worship', color: '#ad2831' },
    { name: 'Relief', color: '#86bbd8' },
    { name: 'Wish', color: '#ffea00' },
    { name: 'Anxiety', color: '#ffc300' },
    { name: 'Aesthetic appreciation', color: '#735d78' },
    { name: 'Ecstasy', color: '#d90368' },
    { name: 'Calmness', color: '#33658a' },
    { name: 'Confusion', color: '#212529' },
    { name: 'Desire', color: '#ff5d8f' },
    { name: 'Empathy', color: '#41ead4' },
    { name: 'Astonishment', color: '#252422' },
    { name: 'Estrangement', color: '#d76a03' },
    { name: 'Excitement', color: '#bc4749' },
    { name: 'Horror', color: '#540d6e' },
    { name: 'Envy', color: '#f9dc5c' },
    { name: 'Interest', color: '#f86624' },
    { name: 'Joy', color: '#6e44ff' },
    { name: 'Fear', color: '#000814' },
    { name: 'Disgust', color: '#8ea604' },
    { name: 'Nostalgy', color: '#ffc482' },
    { name: 'Anger', color: '#c1121f' }, 
    { name: 'Passion', color: '#800e13' }, 
    { name: 'Satisfaction', color: '#38b000' },
    { name: 'Surprise', color: '#3772ff' },
    { name: 'Boredom', color: '#a4a9ad' },
    { name: 'Sadness', color: '#5e6472' },
];

const newPhysicalSymptoms: NewSymptom[] = [
    { name: 'Intestine', spotId: spotId.root },
    { name: 'Kidneys', spotId: spotId.root },
    { name: 'Fatigue', spotId: spotId.root },
    { name: 'Low Back', spotId: spotId.root },
    { name: 'Anemia', spotId: spotId.root },
    { name: 'Blood Pressure', spotId: spotId.root },

    { name: 'Sex Organ', spotId: spotId.sacral },
    { name: 'Menstrual Issues', spotId: spotId.sacral },
    { name: 'Infertility', spotId: spotId.sacral },
    { name: 'Ovary', spotId: spotId.sacral },
    { name: 'Uterus', spotId: spotId.sacral },
    { name: 'Prostate', spotId: spotId.sacral },

    { name: 'Pancreas', spotId: spotId.solarPlexus },
    { name: 'Diabetes', spotId: spotId.solarPlexus },
    { name: 'Stomach', spotId: spotId.solarPlexus },
    { name: 'Liver', spotId: spotId.solarPlexus },
    { name: 'Vesicle', spotId: spotId.solarPlexus },
    { name: 'Spleen', spotId: spotId.solarPlexus },

    { name: 'Heart', spotId: spotId.heart },
    { name: 'Blood Circulation', spotId: spotId.heart },
    { name: 'Low Immunity', spotId: spotId.heart },
    { name: 'Lymphatic diseases', spotId: spotId.heart },
    { name: 'Immune diseases', spotId: spotId.heart },

    { name: 'Voice', spotId: spotId.throat },
    { name: 'Throat', spotId: spotId.throat },
    { name: 'Lungs', spotId: spotId.throat },
    { name: 'Shortness of breath', spotId: spotId.throat },
    { name: 'Thyroid', spotId: spotId.throat },
    { name: 'Cervical', spotId: spotId.throat },
    { name: 'Teeth', spotId: spotId.throat },
    { name: 'Phobias', spotId: spotId.throat },

    { name: 'Left eye', spotId: spotId.front },
    { name: 'Ears', spotId: spotId.front },
    { name: 'Nose', spotId: spotId.front },
    { name: 'Migraine', spotId: spotId.front },
    { name: 'Sinusitis', spotId: spotId.front },
    { name: 'Allergies', spotId: spotId.front },

    { name: 'Insomnia', spotId: spotId.crown },
    { name: 'Tumors', spotId: spotId.crown },
    { name: 'Depression', spotId: spotId.crown },
    { name: 'Right eye', spotId: spotId.crown },
    { name: 'Premature aging', spotId: spotId.crown },  
];

const newEmotionalSymptoms: NewSymptom[] = [
    { name: 'Aggressiveness', spotId: spotId.root },
    { name: 'Violence', spotId: spotId.root },
    { name: 'Self-centeredness', spotId: spotId.root },
    { name: 'Melancholy', spotId: spotId.root },
    { name: 'Strong passions', spotId: spotId.root },
    { name: 'Lack of objectivity', spotId: spotId.root },
    { name: 'Dissatisfaction', spotId: spotId.root },

    { name: 'Insecurity', spotId: spotId.sacral },
    { name: 'Fear', spotId: spotId.sacral },
    { name: 'Sadness', spotId: spotId.sacral },
    { name: 'Anger', spotId: spotId.sacral },
    { name: 'Envy', spotId: spotId.sacral },
    { name: 'Selfishness', spotId: spotId.sacral },
    { name: 'Denial', spotId: spotId.sacral },
    { name: 'Coldness', spotId: spotId.sacral },
    { name: 'Isolation', spotId: spotId.sacral },

    { name: 'Anxiety', spotId: spotId.solarPlexus },
    { name: 'Possessiveness', spotId: spotId.solarPlexus },
    { name: 'Jealousy', spotId: spotId.solarPlexus },
    { name: 'Prejudice', spotId: spotId.solarPlexus },
    { name: 'Wrath', spotId: spotId.solarPlexus },
    { name: 'Attachment', spotId: spotId.solarPlexus },
    { name: 'Pride', spotId: spotId.heart },

    { name: 'Indifference', spotId: spotId.heart },
    { name: 'Low esteem', spotId: spotId.heart },
    { name: 'Inferiority', spotId: spotId.heart },
    { name: 'Radicalism', spotId: spotId.heart },
    { name: 'Guilt', spotId: spotId.heart },
    { name: 'Difficulty relating', spotId: spotId.heart },

    { name: 'Recent memory loss', spotId: spotId.throat },
    { name: 'Lack of presence', spotId: spotId.throat },
    { name: 'Lack of reasoning', spotId: spotId.throat },
    { name: 'Cowardness', spotId: spotId.throat },
    { name: 'Shyness', spotId: spotId.throat },
    { name: 'Blathering', spotId: spotId.throat },
    { name: 'Bad intentions', spotId: spotId.throat },
    { name: 'Intellectual Manipulation', spotId: spotId.throat },
    { name: 'Judgment', spotId: spotId.throat },
    { name: 'Prepotency', spotId: spotId.throat },
    { name: 'Mockness', spotId: spotId.throat },

    { name: 'Rigid Thinking', spotId: spotId.front },
    { name: 'Stubbornness', spotId: spotId.front },
    { name: 'Nightmares', spotId: spotId.front },
    { name: 'Fixation', spotId: spotId.front },
    { name: 'Meanness', spotId: spotId.front },
    { name: 'Lack of faith', spotId: spotId.front },
    { name: 'Arrogance', spotId: spotId.front },
    { name: 'Conscious manipulation', spotId: spotId.front },
    { name: 'Victimization', spotId: spotId.front },
    { name: 'Disorientation', spotId: spotId.front },

    { name: 'Lack of purpose', spotId: spotId.crown },
    { name: 'Disenchantment', spotId: spotId.crown },
    { name: 'Negativity', spotId: spotId.crown },
    { name: 'Self pity', spotId: spotId.crown },
    { name: 'Separateness', spotId: spotId.crown },
    { name: 'Suffering', spotId: spotId.crown },
    { name: 'Solitude', spotId: spotId.crown },
    { name: 'Anguish', spotId: spotId.crown },  
];

export default {
    newMoods,
    newSpots,
    newEmotions,
    newPhysicalSymptoms,
    newEmotionalSymptoms
}